In [10]:
import pickle
import numpy as np
import joblib

In [12]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl','rb'))
# clf = pickle.load(open('model/clf.pkl','rb'))
# save model
joblib.dump(clf, "model/clf.pkl")

# load model (alternate of pickle.load)
clf = joblib.load("model/clf.pkl")


In [13]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [14]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
# Upgrade scikit-learn to latest version to fix '_infrequent_enabled' erro

# test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

from sklearn.preprocessing import OneHotEncoder

# create new OneHotEncoder in sklearn 1.7.1
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# # fit it again on your training data
# ohe_sex.fit(X_train[['Sex']])

# now you can safely transform test data
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, -1))


NameError: name 'X_train_transformed' is not defined

In [24]:
test_input_sex

array([[0., 1.]])

In [25]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [26]:
test_input_embarked

array([[0., 0., 1.]])

In [14]:
test_input_age = test_input[:,2].reshape(1,1)

In [27]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [28]:
test_input_transformed.shape

(1, 10)

In [29]:
clf.predict(test_input_transformed)

array([1], dtype=int64)